name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger deployment on 'main' branch push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up SSH key for EC2 connection
      - name: Set up SSH key
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

      # Deploy code to EC2 instance
      - name: Deploy to EC2
        run: |
          scp -i private_key.pem -r ./ * ubuntu@$EC2_BACKEND_IP:/var/www/myapp
          
          # Restart service (example: Apache)
          ssh -i private_key.pem ubuntu@$EC2_BACKEND_IP "sudo systemctl restart apache2"
