name: Deploy Frontend & Backend to EC2

on:
  push:
    branches:
      - dev  # Change this to your deployment branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      ### 🏗️ Build Frontend (Vite) ###
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Build Frontend
        run: |
          cd frontend
          npm run build

      ### 🚀 Deploy Frontend to EC2 ###
      - name: Deploy Frontend via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_FRONTEND_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "frontend/dist/*"
          target: "/var/www/html"

      ### 🐍 Deploy Backend to EC2 ###
      - name: Deploy Backend via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_BACKEND_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "backend/*"
          target: "~/backend"

      ### 🔄 Restart Backend ###
      - name: Restart Backend
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_BACKEND_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/backend
            source venv/bin/activate  # Activate virtualenv if used
            pip install -r requirements.txt  # Install dependencies

      ### 🔄 Restart Backend apache2 ###
      - name: Restart apache2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_BACKEND_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl restart apache2
            
 ### 🔄 Restart Frontend apache2 ###
      - name: Restart apache2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_FRONTEND_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl restart apache2
