#### FRONTEND DEPLOYMENT ####
- name: Set up Node.js
  uses: actions/setup-node@v3
  with:
    node-version: 18

- name: Validate Frontend Directory
  run: ls -la ./frontend

- name: Install Frontend Dependencies
  working-directory: ./frontend
  run: npm install

- name: Build Frontend
  working-directory: ./frontend
  run: npm run build

- name: Deploy Frontend to EC2 with Apache
  run: |
    echo "$SSH_KEY" > private_key.pem
    chmod 600 private_key.pem
    scp -i private_key.pem -r ./frontend/build/* ubuntu@$FRONTEND_EC2_HOST:$FRONTEND_PATH
    ssh -i private_key.pem ubuntu@$FRONTEND_EC2_HOST "sudo systemctl restart apache2"
